kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-gitops
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 8080
  - containerPort: 30950
    hostPort: 80