apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-vcluster
  namespace: cloud-infra
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: development
  source:
    path: dev-resources/argocd-service/infra/development
    repoURL: https://github.com/felipe88alves/sortKeyHttpServer.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    # namespace: cloud-infra
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

